import type { Plant } from './definitions';

export const plants: Plant[] = [
  {
    id: '1',
    name: 'Snake Plant',
    species: 'Sansevieria trifasciata',
    image: 'https://picsum.photos/400/300?random=1',
    availability: 'In Stock',
    light: 'low',
    water: 'low',
    size: 'medium',
    careInstructions: 'Extremely tolerant and easy to care for. Water only when the soil is completely dry. Thrives on neglect.',
  },
  {
    id: '2',
    name: 'Fiddle Leaf Fig',
    species: 'Ficus lyrata',
    image: 'https://picsum.photos/400/300?random=2',
    availability: 'In Stock',
    light: 'high',
    water: 'medium',
    size: 'large',
    careInstructions: 'Loves bright, indirect light. Water when the top inch of soil is dry. Avoid cold drafts and sudden temperature changes.',
  },
  {
    id: '3',
    name: 'ZZ Plant',
    species: 'Zamioculcas zamiifolia',
    image: 'https://picsum.photos/400/300?random=3',
    availability: 'Out of Stock',
    light: 'low',
    water: 'low',
    size: 'medium',
    careInstructions: 'Drought-tolerant and accepts low-light conditions. Water sparingly, allowing soil to dry out between waterings. Great for beginners.',
  },
  {
    id: '4',
    name: 'Monstera Deliciosa',
    species: 'Monstera deliciosa',
    image: 'https://picsum.photos/400/300?random=4',
    availability: 'In Stock',
    light: 'medium',
    water: 'medium',
    size: 'large',
    careInstructions: 'Prefers bright, indirect light. Water every 1-2 weeks. Its iconic split leaves develop with age and proper light.',
  },
  {
    id: '5',
    name: 'Pothos',
    species: 'Epipremnum aureum',
    image: 'https://picsum.photos/400/300?random=5',
    availability: 'In Stock',
    light: 'low',
    water: 'medium',
    size: 'small',
    careInstructions: 'A forgiving and versatile plant that can thrive in various light conditions. Water when the top of the soil is dry. Easy to propagate.',
  },
  {
    id: '6',
    name: 'Spider Plant',
    species: 'Chlorophytum comosum',
    image: 'https://picsum.photos/400/300?random=6',
    availability: 'In Stock',
    light: 'medium',
    water: 'medium',
    size: 'small',
    careInstructions: 'Adaptable and easy to grow. Prefers bright, indirect light. Produces "spiderettes" which can be repotted.',
  },
];
